/// Flutter icons CustomerMainIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomerMainIcons
///      fonts:
///       - asset: fonts/CustomerMainIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomerMainIcons {
  CustomerMainIcons._();

  static const _kFontFam = 'CustomerMainIcons';

  static const IconData file = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData document = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData marvelBattery = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
  static const IconData ratingStars = IconData(
    0xe803,
    fontFamily: _kFontFam,
  );
}
